-- Heartbeat Insights Table — Sprint 37 P3
-- Stores proactive insights generated by the background heartbeat

create table if not exists heartbeat_insights (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  insight text not null,
  is_actionable boolean not null default true,
  created_at timestamp with time zone default now() not null,
  read_at timestamp with time zone,

  -- Metadata
  context_snapshot jsonb, -- Stores the app context that generated this insight
  frequency_setting text  -- Which heartbeat setting triggered this ('morning', 'evening', 'hourly', 'custom')
);

-- Index for user queries
create index if not exists heartbeat_insights_user_id_idx on heartbeat_insights(user_id);
create index if not exists heartbeat_insights_created_at_idx on heartbeat_insights(created_at desc);

-- RLS policies
alter table heartbeat_insights enable row level security;

create policy "Users can view their own heartbeat insights"
  on heartbeat_insights for select
  using (auth.uid() = user_id);

create policy "Users can insert their own heartbeat insights"
  on heartbeat_insights for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own heartbeat insights"
  on heartbeat_insights for update
  using (auth.uid() = user_id);

create policy "Users can delete their own heartbeat insights"
  on heartbeat_insights for delete
  using (auth.uid() = user_id);
